### ISSUE TITLE
added PKGBUILD 

### ISSUE THREAD

**Issue by cyrinux** [pigmonkey/nmtrust#4]
Hi man, 
thanks for you cool repos and stuff :)
I have created the PKGBUILD for nmtrust, do you want to be a co-maintainer?

https://aur.archlinux.org/packages/nmtrust-git

Thanks you !

**Comment by pigmonkey** [comment]
Thanks for doing that. I just tagged a release in case anyone wants a non-git version.

Sure, I'll co-maintain it.
